;;-*-coding: utf-8;-*-
(define-abbrev-table 'Buffer-menu-mode-abbrev-table '())

(define-abbrev-table 'Custom-mode-abbrev-table '())

(define-abbrev-table 'amrita-mode-abbrev-table '())

(define-abbrev-table 'apache-mode-abbrev-table '())

(define-abbrev-table 'apropos-mode-abbrev-table '())

(define-abbrev-table 'asdf-mode-abbrev-table '())

(define-abbrev-table 'awk-mode-abbrev-table
  '(
   ))

(define-abbrev-table 'bbdb-mode-abbrev-table '())

(define-abbrev-table 'bibtex-mode-abbrev-table '())

(define-abbrev-table 'bmkp-edit-bookmark-record-mode-abbrev-table '())

(define-abbrev-table 'bmkp-edit-bookmark-records-mode-abbrev-table '())

(define-abbrev-table 'bmkp-edit-tags-mode-abbrev-table '())

(define-abbrev-table 'bookmark-bmenu-mode-abbrev-table '())

(define-abbrev-table 'browse-kill-ring-edit-mode-abbrev-table '())

(define-abbrev-table 'browse-kill-ring-mode-abbrev-table '())

(define-abbrev-table 'bs-mode-abbrev-table '())

(define-abbrev-table 'bsh-script-mode-abbrev-table '())

(define-abbrev-table 'c++-mode-abbrev-table
  '(
   ))

(define-abbrev-table 'c-mode-abbrev-table
  '(
   ))

(define-abbrev-table 'calculator-mode-abbrev-table '())

(define-abbrev-table 'calendar-mode-abbrev-table '())

(define-abbrev-table 'change-log-mode-abbrev-table '())

(define-abbrev-table 'comint-mode-abbrev-table '())

(define-abbrev-table 'completion-list-mode-abbrev-table '())

(define-abbrev-table 'conf-colon-mode-abbrev-table '())

(define-abbrev-table 'conf-javaprop-mode-abbrev-table '())

(define-abbrev-table 'conf-ppd-mode-abbrev-table '())

(define-abbrev-table 'conf-space-mode-abbrev-table '())

(define-abbrev-table 'conf-unix-mode-abbrev-table '())

(define-abbrev-table 'conf-windows-mode-abbrev-table '())

(define-abbrev-table 'conf-xdefaults-mode-abbrev-table '())

(define-abbrev-table 'css-mode-abbrev-table '())

(define-abbrev-table 'cssh-mode-abbrev-table '())

(define-abbrev-table 'csv-mode-abbrev-table '())

(define-abbrev-table 'cvs-mode-abbrev-table '())

(define-abbrev-table 'cython-mode-abbrev-table '())

(define-abbrev-table 'define-abbrev-table '())

(define-abbrev-table 'diary-fancy-display-mode-abbrev-table '())

(define-abbrev-table 'diary-mode-abbrev-table '())

(define-abbrev-table 'diff-mode-abbrev-table '())

(define-abbrev-table 'dig-mode-abbrev-table '())

(define-abbrev-table 'diredp-w32-drives-mode-abbrev-table '())

(define-abbrev-table 'display-time-world-mode-abbrev-table '())

(define-abbrev-table 'docTeX-mode-abbrev-table '())

(define-abbrev-table 'doctex-mode-abbrev-table '())

(define-abbrev-table 'dot-eproject-mode-abbrev-table '())

(define-abbrev-table 'drupal-mode-abbrev-table '())

(define-abbrev-table 'dsssl-mode-abbrev-table '())

(define-abbrev-table 'dvc-diff-mode-abbrev-table '())

(define-abbrev-table 'dvc-info-buffer-mode-abbrev-table '())

(define-abbrev-table 'dvc-log-buffer-mode-abbrev-table '())

(define-abbrev-table 'dvc-log-edit-mode-abbrev-table '())

(define-abbrev-table 'dvc-process-buffer-mode-abbrev-table '())

(define-abbrev-table 'dvc-revlist-mode-abbrev-table '())

(define-abbrev-table 'dvc-status-mode-abbrev-table '())

(define-abbrev-table 'dvc-tips-mode-abbrev-table '())

(define-abbrev-table 'ebrowse-electric-list-mode-abbrev-table '())

(define-abbrev-table 'ebrowse-electric-position-mode-abbrev-table '())

(define-abbrev-table 'ebrowse-member-mode-abbrev-table '())

(define-abbrev-table 'ebrowse-tree-mode-abbrev-table '())

(define-abbrev-table 'edebug-eval-mode-abbrev-table '())

(define-abbrev-table 'emacs-lisp-byte-code-mode-abbrev-table '())

(define-abbrev-table 'emacs-lisp-mode-abbrev-table '())

(define-abbrev-table 'erc-dcc-chat-mode-abbrev-table '())

(define-abbrev-table 'erc-list-menu-mode-abbrev-table '())

(define-abbrev-table 'erc-mode-abbrev-table
  '(
    ("bottom" "⊥" nil 3)
   ))

(define-abbrev-table 'erc-nicklist-mode-abbrev-table '())

(define-abbrev-table 'eshell-mode-abbrev-table
  '(
    ("8de" "drush --uri=\"$uri\" uli" nil 3)
   ))

(define-abbrev-table 'finder-mode-abbrev-table '())

(define-abbrev-table 'flycheck-error-list-mode-abbrev-table '())

(define-abbrev-table 'fundamental-mode-abbrev-table '())

(define-abbrev-table 'gfm-mode-abbrev-table '())

(define-abbrev-table 'gist-list-mode-abbrev-table '())

(define-abbrev-table 'global-abbrev-table
  '(
    ("Canon" "Cañon" nil 0)
    ("Rushcoff" "Rushkoff" nil 1)
    ("WATCHDOG" "watchdog('debug', '<pre>'. print_r($view, TRUE) .'</pre>');" nil 0)
    ("Zuckerburg" "Zuckerberg" nil 1)
    ("abbout" "about" nil 0)
    ("abotu" "about" nil 0)
    ("abouta" "about a" nil 0)
    ("aboutit" "about it" nil 0)
    ("aboutthe" "about the" nil 0)
    ("abscence" "absence" nil 0)
    ("accesories" "accessories" nil 0)
    ("accidant" "accident" nil 0)
    ("accomodate" "accommodate" nil 0)
    ("accordingto" "according to" nil 0)
    ("accross" "across" nil 0)
    ("acdc" "AC⚡DC" nil 0)
    ("acheive" "achieve" nil 0)
    ("acheived" "achieved" nil 0)
    ("acheiving" "achieving" nil 0)
    ("acn" "can" nil 0)
    ("acommodate" "accommodate" nil 0)
    ("acomodate" "accommodate" nil 0)
    ("acomplished" "accomplished" nil 0)
    ("actualyl" "actually" nil 0)
    ("acurate" "accurate" nil 0)
    ("addictional" "additional" nil 0)
    ("additinal" "additional" nil 0)
    ("addtional" "additional" nil 0)
    ("addtions" "additions" nil 0)
    ("adequit" "adequate" nil 0)
    ("adequite" "adequate" nil 0)
    ("adn" "and" nil 0)
    ("adresses" "addresses" nil 1)
    ("advanage" "advantage" nil 0)
    ("affraid" "afraid" nil 0)
    ("afterthe" "after the" nil 0)
    ("aganist" "against" nil 0)
    ("aggresive" "aggressive" nil 0)
    ("agian" "again" nil 0)
    ("agreemeent" "agreement" nil 0)
    ("agreemeents" "agreements" nil 0)
    ("agreemnet" "agreement" nil 0)
    ("agreemnets" "agreements" nil 0)
    ("agressive" "aggressive" nil 0)
    ("ahppen" "happen" nil 0)
    ("ahve" "have" nil 3)
    ("allwasy" "always" nil 0)
    ("allwyas" "always" nil 0)
    ("almots" "almost" nil 0)
    ("almsot" "almost" nil 0)
    ("alomst" "almost" nil 0)
    ("alot" "a lot" nil 0)
    ("alpha" "α" nil 4)
    ("alraedy" "already" nil 0)
    ("alreayd" "already" nil 0)
    ("alreday" "already" nil 0)
    ("alwasy" "always" nil 0)
    ("alwats" "always" nil 0)
    ("alway" "always" nil 0)
    ("alwyas" "always" nil 0)
    ("amde" "made" nil 0)
    ("ameria" "America" nil 0)
    ("amke" "make" nil 0)
    ("amkes" "makes" nil 0)
    ("anbd" "and" nil 0)
    ("andone" "and one" nil 0)
    ("andt he" "and the" nil 0)
    ("andteh" "and the" nil 0)
    ("andthe" "and the" nil 0)
    ("anonyminity" "anonymity" nil 0)
    ("anothe" "another" nil 0)
    ("anual" "annual" nil 0)
    ("apache" "Apache" nil 4)
    ("apparant" "apparent" nil 0)
    ("apparrent" "apparent" nil 0)
    ("appearence" "appearance" nil 0)
    ("appeares" "appears" nil 0)
    ("applicaiton" "application" nil 0)
    ("applicaitons" "applications" nil 0)
    ("applicatns" "applicants" nil 1)
    ("applyed" "applied" nil 0)
    ("appointiment" "appointment" nil 0)
    ("approrpiate" "appropriate" nil 0)
    ("approrpriate" "appropriate" nil 0)
    ("aquisition" "acquisition" nil 0)
    ("aquisitions" "acquisitions" nil 0)
    ("arent" "aren't" nil 0)
    ("arguement" "argument" nil 0)
    ("arguements" "arguments" nil 0)
    ("ari" "¡arriba!" nil 1)
    ("arnt" "aren't" nil 0)
    ("arond" "around" nil 0)
    ("artical" "article" nil 0)
    ("articel" "article" nil 0)
    ("asdvertising" "advertising" nil 0)
    ("assistent" "assistant" nil 0)
    ("asthe" "as the" nil 0)
    ("asthetic" "aesthetic" nil 1)
    ("atention" "attention" nil 0)
    ("atmospher" "atmosphere" nil 0)
    ("attentioin" "attention" nil 0)
    ("atthe" "at the" nil 0)
    ("audeince" "audience" nil 0)
    ("audiance" "audience" nil 0)
    ("authetication" "authentication" nil 0)
    ("availalbe" "available" nil 0)
    ("awya" "away" nil 0)
    ("aywa" "away" nil 0)
    ("bakc" "back" nil 0)
    ("balence" "balance" nil 0)
    ("ballance" "balance" nil 0)
    ("baout" "about" nil 0)
    ("bcak" "back" nil 0)
    ("beacause" "because" nil 0)
    ("beacuse" "because" nil 0)
    ("becasue" "because" nil 1)
    ("becaus" "because" nil 0)
    ("becausea" "because a" nil 0)
    ("becauseof" "because of" nil 0)
    ("becausethe" "because the" nil 0)
    ("becauseyou" "because you" nil 0)
    ("becomeing" "becoming" nil 0)
    ("becomming" "becoming" nil 0)
    ("becuase" "because" nil 0)
    ("becuse" "because" nil 0)
    ("befoer" "before" nil 0)
    ("beggining" "beginning" nil 0)
    ("begining" "beginning" nil 0)
    ("beginining" "beginning" nil 0)
    ("behabviour" "behaviour" nil 0)
    ("behaivior" "behaviour" nil 0)
    ("behavour" "behaviour" nil 0)
    ("beleiev" "believe" nil 0)
    ("beleieve" "believe" nil 0)
    ("beleif" "belief" nil 0)
    ("beleive" "believe" nil 6)
    ("beleived" "believed" nil 0)
    ("beleives" "believes" nil 0)
    ("beliefe" "belief" nil 0)
    ("beliveve" "believe" nil 0)
    ("benifit" "benefit" nil 0)
    ("benifits" "benefits" nil 0)
    ("beta" "β" nil 0)
    ("betwen" "between" nil 0)
    ("beutiful" "beautiful" nil 0)
    ("blase" "blase" nil 0)
    ("bod" "bodacious" nil 1)
    ("boxs" "boxes" nil 0)
    ("brekfast" "breakfast" nil 0)
    ("brodcast" "broadcast" nil 0)
    ("butthe" "but the" nil 0)
    ("bve" "be" nil 0)
    ("cafe" "cafe" nil 0)
    ("caharcter" "character" nil 0)
    ("calcullated" "calculated" nil 0)
    ("calulated" "calculated" nil 0)
    ("candidtae" "candidate" nil 0)
    ("candidtaes" "candidates" nil 0)
    ("canon" "cañon" nil 1)
    ("caontains" "contains" nil 0)
    ("capabilites" "capabilities" nil 0)
    ("cappucinno" "tall double half-caf whole milk cappuccino" nil 0)
    ("catagory" "category" nil 0)
    ("categiory" "category" nil 0)
    ("centery" "century" nil 1)
    ("certian" "certain" nil 0)
    ("challange" "challenge" nil 0)
    ("challanges" "challenges" nil 0)
    ("chaneg" "change" nil 0)
    ("chanegs" "changes" nil 0)
    ("changable" "changeable" nil 0)
    ("changeing" "changing" nil 0)
    ("changng" "changing" nil 0)
    ("charachter" "character" nil 0)
    ("charachters" "characters" nil 0)
    ("charactor" "character" nil 0)
    ("charecter" "character" nil 0)
    ("charector" "character" nil 0)
    ("cheif" "chief" nil 0)
    ("chekc" "check" nil 0)
    ("chnage" "change" nil 0)
    ("cieling" "ceiling" nil 0)
    ("circut" "circuit" nil 0)
    ("claer" "clear" nil 0)
    ("claered" "cleared" nil 0)
    ("claerly" "clearly" nil 0)
    ("cliant" "client" nil 0)
    ("cliche" "cliche" nil 0)
    ("cna" "can" nil 0)
    ("colection" "collection" nil 0)
    ("comanies" "companies" nil 0)
    ("comany" "company" nil 0)
    ("comapnies" "companies" nil 0)
    ("comapny" "company" nil 0)
    ("combintation" "combination" nil 0)
    ("comited" "committed" nil 0)
    ("comittee" "committee" nil 0)
    ("commadn" "command" nil 0)
    ("comming" "coming" nil 0)
    ("commitee" "committee" nil 0)
    ("committe" "committee" nil 0)
    ("committment" "commitment" nil 0)
    ("committments" "commitments" nil 0)
    ("committy" "committee" nil 0)
    ("comntain" "contain" nil 0)
    ("comntains" "contains" nil 0)
    ("compair" "compare" nil 0)
    ("compatable" "compatible" nil 0)
    ("compleated" "completed" nil 0)
    ("compleatly" "completely" nil 0)
    ("compleatness" "completeness" nil 0)
    ("completly" "completely" nil 0)
    ("completness" "completeness" nil 0)
    ("complteted" "completed" nil 0)
    ("composate" "composite" nil 0)
    ("compteted" "completed" nil 0)
    ("comtain" "contain" nil 0)
    ("comtains" "contains" nil 0)
    ("comunicate" "communicate" nil 0)
    ("comunity" "community" nil 0)
    ("condersider" "consider" nil 0)
    ("condolances" "condolences" nil 0)
    ("conected" "connected" nil 0)
    ("conferance" "conference" nil 0)
    ("configration" "configuration" nil 0)
    ("confirmmation" "confirmation" nil 0)
    ("conjuntion" "conjunction" nil 0)
    ("considerit" "considerate" nil 0)
    ("considerite" "considerate" nil 0)
    ("consistant" "consistent" nil 1)
    ("consonent" "consonant" nil 0)
    ("conspiricy" "conspiracy" nil 0)
    ("constuction" "construction" nil 0)
    ("consultent" "consultant" nil 0)
    ("consumeable" "consumable" nil 0)
    ("contitions" "conditions" nil 0)
    ("controlable" "controllable" nil 0)
    ("contructed" "constructed" nil 1)
    ("convertable" "convertible" nil 0)
    ("cooparate" "cooperate" nil 0)
    ("cooporate" "cooperate" nil 0)
    ("corproation" "corporation" nil 0)
    ("corproations" "corporations" nil 0)
    ("corrospond" "correspond" nil 0)
    ("corruptable" "corruptible" nil 0)
    ("cotten" "cotton" nil 0)
    ("coudl" "could" nil 0)
    ("coudln" "couldn" nil 0)
    ("coudn" "couldn" nil 0)
    ("couldnt" "couldn't" nil 0)
    ("couldthe" "could the" nil 0)
    ("cowa" "¡Cowabunga, Dude!" nil 5)
    ("cpoy" "copy" nil 0)
    ("creme" "creme" nil 0)
    ("ctaegory" "category" nil 0)
    ("cusotmer" "customer" nil 0)
    ("cusotmers" "customers" nil 0)
    ("cutlural" "cultural" nil 1)
    ("cutsomer" "customer" nil 0)
    ("cutsomers" "customers" nil 0)
    ("cxan" "can" nil 0)
    ("danceing" "dancing" nil 0)
    ("dcument" "document" nil 0)
    ("deatils" "details" nil 0)
    ("decison" "decision" nil 0)
    ("decisons" "decisions" nil 0)
    ("decor" "decor" nil 0)
    ("defendent" "defendant" nil 0)
    ("definately" "definitely" nil 0)
    ("definatley" "definitely" nil 0)
    ("definded" "defined" nil 0)
    ("delimna" "dilemma" nil 0)
    ("delta" "δ" nil 1)
    ("dependances" "dependencies" nil 0)
    ("deptartment" "department" nil 0)
    ("desicion" "decision" nil 0)
    ("desicions" "decisions" nil 0)
    ("desing" "design" nil 1)
    ("desision" "decision" nil 0)
    ("desisions" "decisions" nil 0)
    ("detente" "detente" nil 0)
    ("determin" "determine" nil 0)
    ("determins" "determine" nil 0)
    ("develeoprs" "developers" nil 0)
    ("devellop" "develop" nil 0)
    ("develloped" "developed" nil 0)
    ("develloper" "developer" nil 0)
    ("devellopers" "developers" nil 0)
    ("develloping" "developing" nil 0)
    ("devellopment" "development" nil 0)
    ("devellopments" "developments" nil 0)
    ("devellops" "develop" nil 0)
    ("develope" "develop" nil 0)
    ("developement" "development" nil 0)
    ("developements" "developments" nil 0)
    ("developor" "developer" nil 0)
    ("developors" "developers" nil 0)
    ("develpment" "development" nil 0)
    ("devloped" "developed" nil 0)
    ("dh" "Damon Haley" nil 4)
    ("diaplay" "display" nil 0)
    ("didint" "didn't" nil 0)
    ("didnot" "did not" nil 0)
    ("didnt" "didn't" nil 0)
    ("difefrent" "different" nil 0)
    ("diferences" "differences" nil 0)
    ("differance" "difference" nil 0)
    ("differances" "differences" nil 0)
    ("differant" "different" nil 0)
    ("differemt" "different" nil 0)
    ("differnt" "different" nil 0)
    ("diffrent" "different" nil 0)
    ("directer" "director" nil 0)
    ("directers" "directors" nil 0)
    ("directiosn" "direction" nil 0)
    ("disapproval" "ಠ_ಠ" nil 0)
    ("disatisfied" "dissatisfied" nil 0)
    ("discoverd" "discovered" nil 0)
    ("disign" "design" nil 0)
    ("dispaly" "display" nil 0)
    ("dissonent" "dissonant" nil 0)
    ("distribusion" "distribution" nil 0)
    ("distrubution" "distribution" nil 0)
    ("divsion" "division" nil 0)
    ("docs" "documents" nil 0)
    ("docuement" "documents" nil 0)
    ("docuemnt" "document" nil 0)
    ("documetn" "document" nil 0)
    ("documnet" "document" nil 0)
    ("documnets" "documents" nil 0)
    ("doese" "does" nil 0)
    ("doesnt" "doesn't" nil 0)
    ("doign" "doing" nil 0)
    ("doimg" "doing" nil 0)
    ("doind" "doing" nil 0)
    ("dollers" "dollars" nil 0)
    ("donig" "doing" nil 0)
    ("dont" "don't" nil 0)
    ("dosnt" "doesn't" nil 0)
    ("driveing" "driving" nil 0)
    ("drnik" "drink" nil 0)
    ("eclair" "eclair" nil 0)
    ("ediquite" "etiquette" nil 0)
    ("efel" "feel" nil 0)
    ("effecient" "efficient" nil 0)
    ("efort" "effort" nil 0)
    ("eforts" "efforts" nil 0)
    ("eg" "ℯℊ" nil 0)
    ("eh" "the" nil 1)
    ("ehr" "her" nil 0)
    ("eligable" "eligible" nil 0)
    ("embarass" "embarrass" nil 0)
    ("emigre" "emigre" nil 0)
    ("enahancements" "enhancements" nil 0)
    ("english" "English" nil 0)
    ("enought" "enough" nil 1)
    ("entree" "entree" nil 0)
    ("equippment" "equipment" nil 0)
    ("equivalant" "equivalent" nil 0)
    ("esle" "else" nil 0)
    ("especally" "especially" nil 0)
    ("especialyl" "especially" nil 0)
    ("espesially" "especially" nil 0)
    ("excellant" "excellent" nil 0)
    ("excercise" "exercise" nil 0)
    ("exchagne" "exchange" nil 0)
    ("exchagnes" "exchanges" nil 0)
    ("excitment" "excitement" nil 0)
    ("exhcange" "exchange" nil 0)
    ("exhcanges" "exchanges" nil 0)
    ("experiance" "experience" nil 0)
    ("experienc" "experience" nil 0)
    ("explicitely" "explicitly" nil 1)
    ("exprience" "experience" nil 0)
    ("exprienced" "experienced" nil 0)
    ("eyeroll" "◔_◔" nil 1)
    ("eyt" "yet" nil 0)
    ("facade" "facade" nil 0)
    ("faeture" "feature" nil 0)
    ("faetures" "features" nil 0)
    ("familair" "familiar" nil 0)
    ("familar" "familiar" nil 0)
    ("familliar" "familiar" nil 0)
    ("fammiliar" "familiar" nil 0)
    ("feild" "field" nil 0)
    ("feilds" "fields" nil 0)
    ("fianlly" "finally" nil 0)
    ("fidn" "find" nil 0)
    ("fifith" "fifth" nil 0)
    ("finalyl" "finally" nil 0)
    ("finnally" "finally" nil 0)
    ("finnish" "finish" nil 0)
    ("firends" "friends" nil 0)
    ("firts" "first" nil 0)
    ("fitler" "filter" nil 1)
    ("fixit" "fix it" nil 0)
    ("follwo" "follow" nil 0)
    ("follwoing" "following" nil 2)
    ("foloowing" "following" nil 0)
    ("fora" "for a" nil 0)
    ("foriegn" "foreign" nil 0)
    ("forthe" "for the" nil 0)
    ("forwrd" "forward" nil 0)
    ("forwrds" "forwards" nil 0)
    ("foudn" "found" nil 0)
    ("foward" "forward" nil 0)
    ("fowards" "forwards" nil 0)
    ("freind" "friend" nil 0)
    ("freindly" "friendly" nil 0)
    ("freinds" "friends" nil 0)
    ("frmo" "from" nil 0)
    ("fromt he" "from the" nil 0)
    ("fromthe" "from the" nil 0)
    ("furneral" "funeral" nil 0)
    ("fwe" "few" nil 0)
    ("gamma" "γ" nil 0)
    ("garantee" "guarantee" nil 0)
    ("gaurd" "guard" nil 0)
    ("gemeral" "general" nil 0)
    ("gerat" "great" nil 0)
    ("gerneral" "general" nil 0)
    ("geting" "getting" nil 0)
    ("gettin" "getting" nil 0)
    ("gievn" "given" nil 0)
    ("giveing" "giving" nil 0)
    ("gloabl" "global" nil 0)
    ("goign" "going" nil 0)
    ("gonig" "going" nil 0)
    ("govenment" "government" nil 0)
    ("goverment" "government" nil 0)
    ("gpom" "git pull origin master" nil 3)
    ("gruop" "group" nil 0)
    ("gruops" "groups" nil 0)
    ("grwo" "grow" nil 0)
    ("guidlines" "guidelines" nil 0)
    ("hadbeen" "had been" nil 0)
    ("hadnt" "hadn't" nil 0)
    ("haev" "have" nil 0)
    ("hapen" "happen" nil 0)
    ("hapened" "happened" nil 0)
    ("hapening" "happening" nil 0)
    ("hapens" "happens" nil 0)
    ("happend" "happened" nil 0)
    ("hasbeen" "has been" nil 0)
    ("hasnt" "hasn't" nil 0)
    ("havebeen" "have been" nil 0)
    ("haveing" "having" nil 0)
    ("haven;t" "haven't" nil 0)
    ("hda" "had" nil 0)
    ("hearign" "hearing" nil 0)
    ("heire" "he-ire" nil 0)
    ("helpdesk" "help-desk" nil 0)
    ("helpfull" "helpful" nil 0)
    ("herat" "heart" nil 0)
    ("hesaid" "he said" nil 0)
    ("hewas" "he was" nil 0)
    ("hge" "he" nil 0)
    ("hier" "heir" nil 0)
    ("hismelf" "himself" nil 0)
    ("hiten" "hitting" nil 0)
    ("hitten" "hitting" nil 0)
    ("hlep" "help" nil 0)
    ("howerver" "however" nil 0)
    ("hsa" "has" nil 0)
    ("hsi" "his" nil 0)
    ("hte" "the" nil 0)
    ("htere" "there" nil 0)
    ("htese" "these" nil 0)
    ("htey" "they" nil 0)
    ("hting" "thing" nil 0)
    ("htink" "think" nil 0)
    ("htis" "this" nil 0)
    ("htp:" "http:" nil 0)
    ("http:\\\\" "http://" nil 0)
    ("httpL" "http:" nil 0)
    ("hundre" "hundred" nil 1)
    ("hvae" "have" nil 0)
    ("hvaing" "having" nil 0)
    ("hwich" "which" nil 0)
    ("idae" "idea" nil 0)
    ("idaes" "ideas" nil 0)
    ("identifiy" "identify" nil 0)
    ("identofy" "identify" nil 0)
    ("ihs" "his" nil 0)
    ("imediate" "immediate" nil 0)
    ("imediatly" "immediately" nil 0)
    ("immediatly" "immediately" nil 0)
    ("impilies" "implies" nil 0)
    ("implemenation" "implementation" nil 0)
    ("importent" "important" nil 0)
    ("importnat" "important" nil 0)
    ("impossable" "impossible" nil 0)
    ("improvemnt" "improvement" nil 0)
    ("improvment" "improvement" nil 0)
    ("includ" "include" nil 0)
    ("indecate" "indicate" nil 0)
    ("indenpendence" "independence" nil 0)
    ("indenpendent" "independent" nil 0)
    ("indepedent" "independent" nil 0)
    ("independance" "independence" nil 0)
    ("independant" "independent" nil 0)
    ("inf" "∞" nil 0)
    ("influance" "influence" nil 0)
    ("infomation" "information" nil 0)
    ("informatoin" "information" nil 0)
    ("inital" "initial" nil 0)
    ("initalization" "initialization" nil 0)
    ("ins" "INSERT INTO" nil 2)
    ("instaleld" "installed" nil 0)
    ("insted" "instead" nil 0)
    ("insurence" "insurance" nil 0)
    ("intall" "install" nil 2)
    ("inteh" "in the" nil 0)
    ("interum" "interim" nil 0)
    ("inthe" "in the" nil 0)
    ("inturn" "in turn" nil 0)
    ("invitaion" "invitation" nil 0)
    ("invstigated" "investigated" nil 0)
    ("inwhich" "in which" nil 0)
    ("isnt" "isn't" nil 0)
    ("isthe" "is the" nil 0)
    ("itis" "it is" nil 0)
    ("ititial" "initial" nil 0)
    ("itll" "it'll" nil 0)
    ("itnerest" "interest" nil 0)
    ("itnerested" "interested" nil 0)
    ("itneresting" "interesting" nil 0)
    ("itnerests" "interests" nil 0)
    ("itwas" "it was" nil 0)
    ("ivestigative" "investigative" nil 0)
    ("iwll" "will" nil 0)
    ("iwth" "with" nil 1)
    ("jsut" "just" nil 0)
    ("jugment" "judgment" nil 0)
    ("knowldge" "knowledge" nil 0)
    ("knowlege" "knowledge" nil 0)
    ("knwo" "know" nil 1)
    ("knwon" "known" nil 0)
    ("knwos" "knows" nil 0)
    ("konw" "know" nil 0)
    ("konwn" "known" nil 0)
    ("konws" "knows" nil 0)
    ("labratory" "laboratory" nil 0)
    ("languange" "language" nil 0)
    ("lastyear" "last year" nil 0)
    ("learnign" "learning" nil 0)
    ("lenght" "length" nil 0)
    ("levle" "level" nil 0)
    ("libary" "library" nil 0)
    ("librarry" "library" nil 0)
    ("librery" "library" nil 0)
    ("liek" "like" nil 2)
    ("liekd" "liked" nil 0)
    ("lieutenent" "lieutenant" nil 0)
    ("liev" "live" nil 0)
    ("likly" "likely" nil 0)
    ("lisense" "license" nil 0)
    ("littel" "little" nil 0)
    ("litttle" "little" nil 0)
    ("liuke" "like" nil 0)
    ("liveing" "living" nil 0)
    ("loard" "lord" nil 1)
    ("loev" "love" nil 0)
    ("lonly" "lonely" nil 0)
    ("lookign" "looking" nil 0)
    ("lookup" "look up" nil 0)
    ("maintainence" "maintenance" nil 1)
    ("maintenence" "maintenance" nil 0)
    ("makeing" "making" nil 0)
    ("managment" "management" nil 0)
    ("mantain" "maintain" nil 0)
    ("marraige" "marriage" nil 0)
    ("memeber" "member" nil 0)
    ("merchent" "merchant" nil 0)
    ("mesage" "message" nil 0)
    ("mesages" "messages" nil 0)
    ("mispell" "misspell" nil 0)
    ("mispelling" "misspelling" nil 0)
    ("mispellings" "misspellings" nil 0)
    ("mkae" "make" nil 0)
    ("mkaes" "makes" nil 0)
    ("mkaing" "making" nil 0)
    ("moeny" "money" nil 0)
    ("morgage" "mortgage" nil 0)
    ("mroe" "more" nil 1)
    ("mu" "無" nil 1)
    ("mysefl" "myself" nil 0)
    ("mythologically" "mythologically" nil 2)
    ("myu" "my" nil 0)
    ("naive" "naive" nil 0)
    ("necassarily" "necessarily" nil 0)
    ("necassary" "necessary" nil 0)
    ("neccessarily" "necessarily" nil 0)
    ("neccessary" "necessary" nil 0)
    ("necesarily" "necessarily" nil 0)
    ("necesary" "necessary" nil 0)
    ("negotiaing" "negotiating" nil 0)
    ("nkow" "know" nil 0)
    ("nothign" "nothing" nil 0)
    ("nver" "never" nil 0)
    ("nwe" "new" nil 0)
    ("nwo" "now" nil 0)
    ("obediant" "obedient" nil 0)
    ("ocasion" "occasion" nil 0)
    ("occassion" "occasion" nil 0)
    ("occured" "occurred" nil 0)
    ("occurence" "occurrence" nil 0)
    ("occurences" "occurrences" nil 0)
    ("occurrance" "occurrence" nil 0)
    ("ocur" "occur" nil 0)
    ("odbc" "ODBC" nil 0)
    ("oeprator" "operator" nil 0)
    ("ofits" "of its" nil 0)
    ("ofthe" "of the" nil 0)
    ("oging" "going" nil 0)
    ("ohter" "other" nil 1)
    ("ok" "okily dokily!" nil 13)
    ("ole" "¡ole, olé!" nil 2)
    ("omre" "more" nil 0)
    ("oneof" "one of" nil 0)
    ("onepoint" "one point" nil 0)
    ("online" "on-line" nil 3)
    ("ont he" "on the" nil 0)
    ("onthe" "on the" nil 0)
    ("onyl" "only" nil 0)
    ("opcode" "op-code" nil 0)
    ("operaror" "operator" nil 0)
    ("oppasite" "opposite" nil 0)
    ("opperation" "operation" nil 0)
    ("oppertunity" "opportunity" nil 0)
    ("opposate" "opposite" nil 0)
    ("opposible" "opposable" nil 0)
    ("opposit" "opposite" nil 0)
    ("oppotunities" "opportunities" nil 0)
    ("oppotunity" "opportunity" nil 0)
    ("orginization" "organization" nil 0)
    ("orginized" "organized" nil 0)
    ("originial" "original" nil 0)
    ("orignal" "original" nil 0)
    ("ot" "to" nil 5)
    ("otehr" "other" nil 1)
    ("otu" "out" nil 0)
    ("outof" "out of" nil 0)
    ("overthe" "over the" nil 0)
    ("ovverides" "overrides" nil 0)
    ("owrk" "work" nil 0)
    ("owuld" "would" nil 0)
    ("oxident" "oxidant" nil 0)
    ("papaer" "paper" nil 0)
    ("parliment" "parliament" nil 0)
    ("partof" "part of" nil 0)
    ("paticular" "particular" nil 0)
    ("paymetn" "payment" nil 0)
    ("paymetns" "payments" nil 0)
    ("pciture" "picture" nil 0)
    ("peice" "piece" nil 0)
    ("peices" "pieces" nil 0)
    ("peolpe" "people" nil 0)
    ("peopel" "people" nil 0)
    ("percentof" "percent of" nil 0)
    ("percentto" "percent to" nil 0)
    ("performence" "performance" nil 0)
    ("perhasp" "perhaps" nil 0)
    ("perhpas" "perhaps" nil 0)
    ("permanant" "permanent" nil 0)
    ("perminent" "permanent" nil 0)
    ("perscriptions" "prescriptions" nil 0)
    ("personalyl" "personally" nil 0)
    ("personell" "personnel" nil 0)
    ("phpcs" "phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme sites/all/modules/custom/cu_users/cu_users.module" nil 0)
    ("pleasent" "pleasant" nil 0)
    ("plugin" "plug-in" nil 6)
    ("poeple" "people" nil 0)
    ("porblem" "problem" nil 0)
    ("porblems" "problems" nil 0)
    ("porvide" "provide" nil 0)
    ("possable" "possible" nil 0)
    ("postition" "position" nil 0)
    ("potentialy" "potentially" nil 0)
    ("prefure" "prefer" nil 0)
    ("pregnent" "pregnant" nil 0)
    ("prelease" "release" nil 0)
    ("prerelease" "pre-release" nil 0)
    ("presance" "presence" nil 0)
    ("presnet" "present" nil 1)
    ("prioirities" "priorities" nil 1)
    ("priviledges" "privileges" nil 1)
    ("privleged" "privileged" nil 0)
    ("probelm" "problem" nil 0)
    ("probelms" "problems" nil 0)
    ("problesm" "problems" nil 0)
    ("proceding" "proceeding" nil 0)
    ("proctetion" "protection" nil 0)
    ("prominant" "prominent" nil 0)
    ("prop" "proposal" nil 5)
    ("proposal" "proposal" nil 0)
    ("propsoal" "proposal" nil 3)
    ("protction" "protection" nil 0)
    ("protoge" "protege" nil 0)
    ("psoition" "position" nil 0)
    ("ptogress" "progress" nil 0)
    ("publicising" "publicizing" nil 0)
    ("puting" "putting" nil 0)
    ("pwoer" "power" nil 0)
    ("quater" "quarter" nil 0)
    ("quaters" "quarters" nil 0)
    ("quesion" "question" nil 0)
    ("quesions" "questions" nil 0)
    ("questioms" "questions" nil 0)
    ("questiosn" "questions" nil 0)
    ("questoin" "question" nil 0)
    ("quetion" "question" nil 0)
    ("quetions" "questions" nil 0)
    ("raidus" "RADIUS" nil 0)
    ("realalistically" "realistically" nil 1)
    ("realyl" "really" nil 0)
    ("reccomend" "recommend" nil 1)
    ("reccomendation" "recommendation" nil 1)
    ("reccomendations" "recommendations" nil 0)
    ("reccommend" "recommend" nil 0)
    ("receieve" "receive" nil 0)
    ("recieve" "receive" nil 1)
    ("recieved" "received" nil 4)
    ("recieving" "receiving" nil 0)
    ("recomend" "recommend" nil 0)
    ("recomendation" "recommendation" nil 0)
    ("recomendations" "recommendations" nil 0)
    ("recomended" "recommended" nil 0)
    ("recomending" "recommending" nil 0)
    ("reconize" "recognize" nil 0)
    ("recrod" "record" nil 0)
    ("redirector" "re-director" nil 0)
    ("regardsless" "regardless" nil 0)
    ("regession" "regression" nil 0)
    ("regresion" "regression" nil 0)
    ("reivew" "review" nil 2)
    ("reivewer" "reviewer" nil 3)
    ("releated" "related" nil 0)
    ("religous" "religious" nil 0)
    ("relize" "realize" nil 0)
    ("reloacted" "relocated" nil 0)
    ("reltaed" "related" nil 0)
    ("reluctent" "reluctant" nil 0)
    ("remeber" "remember" nil 0)
    ("reommend" "recommend" nil 0)
    ("representativs" "representatives" nil 0)
    ("representives" "representatives" nil 0)
    ("represetned" "represented" nil 0)
    ("represnt" "represent" nil 0)
    ("requirment" "requirement" nil 0)
    ("requirments" "requirements" nil 0)
    ("reserach" "research" nil 0)
    ("resollution" "resolution" nil 0)
    ("resorces" "resources" nil 0)
    ("respomd" "respond" nil 0)
    ("respomse" "response" nil 0)
    ("responce" "response" nil 0)
    ("responsability" "responsibility" nil 0)
    ("responsable" "responsible" nil 0)
    ("responsibile" "responsible" nil 0)
    ("responsiblity" "responsibility" nil 0)
    ("restaraunt" "restaurant" nil 0)
    ("restuarant" "restaurant" nil 0)
    ("reult" "result" nil 0)
    ("reveiw" "review" nil 0)
    ("reveiwing" "reviewing" nil 0)
    ("rumers" "rumors" nil 0)
    ("runnning" "running" nil 0)
    ("rwite" "write" nil 0)
    ("rythm" "rhythm" nil 0)
    ("saidhe" "said he" nil 0)
    ("saidit" "said it" nil 0)
    ("saidthat" "said that" nil 0)
    ("saidthe" "said the" nil 0)
    ("scedule" "schedule" nil 0)
    ("sceduled" "scheduled" nil 0)
    ("scen" "scene" nil 0)
    ("scol" "scowl" nil 0)
    ("scoli" "scowl" nil 0)
    ("seance" "seance" nil 0)
    ("secratary" "secretary" nil 0)
    ("sectino" "section" nil 0)
    ("securtiy" "security" nil 0)
    ("seh" "she" nil 0)
    ("sel" "SELECT" nil 1)
    ("selectoin" "selection" nil 0)
    ("sentance" "sentence" nil 0)
    ("separeate" "separate" nil 0)
    ("seperate" "separate" nil 0)
    ("seperated" "separated" nil 0)
    ("sercumstances" "circumstances" nil 0)
    ("serveral" "several" nil 0)
    ("sez" "says" nil 0)
    ("shcool" "school" nil 0)
    ("shesaid" "she said" nil 0)
    ("shineing" "shining" nil 0)
    ("shiped" "shipped" nil 0)
    ("shoudl" "should" nil 1)
    ("shouldent" "shouldn't" nil 0)
    ("shouldnt" "shouldn't" nil 0)
    ("showinf" "showing" nil 0)
    ("signifacnt" "significant" nil 0)
    ("simalar" "similar" nil 0)
    ("similiar" "similar" nil 0)
    ("simpilified" "simplified" nil 0)
    ("simpyl" "simply" nil 0)
    ("sincerly" "sincerely" nil 0)
    ("sitll" "still" nil 0)
    ("smae" "same" nil 0)
    ("smoe" "some" nil 0)
    ("soem" "some" nil 1)
    ("sohw" "show" nil 0)
    ("soical" "social" nil 0)
    ("somethign" "something" nil 0)
    ("someting" "something" nil 0)
    ("somewaht" "somewhat" nil 0)
    ("somthing" "something" nil 0)
    ("somtimes" "sometimes" nil 0)
    ("soudn" "sound" nil 0)
    ("soudns" "sounds" nil 0)
    ("speach" "speech" nil 0)
    ("specificaly" "specifically" nil 0)
    ("specificalyl" "specifically" nil 0)
    ("starbucks" "tall double half-caf whole milk cappuccino" nil 1)
    ("statment" "statement" nil 0)
    ("statments" "statements" nil 0)
    ("stnad" "stand" nil 0)
    ("stopry" "story" nil 0)
    ("stoyr" "story" nil 0)
    ("stpo" "stop" nil 0)
    ("strentgh" "strength" nil 0)
    ("stroy" "story" nil 0)
    ("struggel" "struggle" nil 0)
    ("strugle" "struggle" nil 0)
    ("studnet" "student" nil 0)
    ("sublanguange" "sublanguage" nil 0)
    ("substitued" "substituted" nil 0)
    ("successfull" "successful" nil 0)
    ("successfuly" "successfully" nil 0)
    ("successfulyl" "successfully" nil 0)
    ("sucess" "success" nil 0)
    ("sucessfull" "successful" nil 0)
    ("sucsessfully" "successfully" nil 1)
    ("sufficiant" "sufficient" nil 0)
    ("suposed" "supposed" nil 0)
    ("suppossed" "supposed" nil 0)
    ("suprise" "surprise" nil 0)
    ("suprised" "surprised" nil 0)
    ("suprisingly" "surprisingly" nil 0)
    ("sweat" "sweet" nil 1)
    ("swiming" "swimming" nil 0)
    ("tables" "（╯°□°）╯︵ ┻━┻" nil 1)
    ("tahn" "than" nil 0)
    ("taht" "that" nil 0)
    ("talekd" "talked" nil 0)
    ("talior" "tailor" nil 0)
    ("talkign" "talking" nil 0)
    ("tath" "that" nil 0)
    ("tecnical" "technical" nil 0)
    ("teh" "the" nil 1)
    ("tehy" "they" nil 0)
    ("terminiated" "terminated" nil 0)
    ("termoil" "turmoil" nil 0)
    ("tghe" "the" nil 0)
    ("tghis" "this" nil 0)
    ("thansk" "thanks" nil 0)
    ("thatthe" "that the" nil 0)
    ("theatre" "theater" nil 1)
    ("thecompany" "the company" nil 0)
    ("thefirst" "the first" nil 0)
    ("thegovernment" "the government" nil 0)
    ("themself" "themselves" nil 0)
    ("themselfs" "themselves" nil 0)
    ("thenew" "the new" nil 0)
    ("theri" "their" nil 0)
    ("thesame" "the same" nil 0)
    ("theta" "θ" nil 0)
    ("thetwo" "the two" nil 0)
    ("theyll" "they'll" nil 0)
    ("theyve" "they've" nil 0)
    ("thgat" "that" nil 0)
    ("thge" "the" nil 0)
    ("thier" "their" nil 0)
    ("thigsn" "things" nil 0)
    ("thisyear" "this year" nil 0)
    ("thna" "than" nil 0)
    ("thne" "then" nil 0)
    ("thnig" "thing" nil 0)
    ("thnigs" "things" nil 0)
    ("threatend" "threatened" nil 0)
    ("thsi" "this" nil 0)
    ("thsoe" "those" nil 0)
    ("thta" "that" nil 0)
    ("tihs" "this" nil 0)
    ("timne" "time" nil 0)
    ("tiogether" "together" nil 0)
    ("tje" "the" nil 0)
    ("tjhe" "the" nil 0)
    ("tkae" "take" nil 1)
    ("tkaes" "takes" nil 0)
    ("tkaing" "taking" nil 0)
    ("tlaking" "talking" nil 0)
    ("todya" "today" nil 0)
    ("togehter" "together" nil 0)
    ("tomorow" "tomorrow" nil 0)
    ("tongiht" "tonight" nil 0)
    ("tonihgt" "tonight" nil 0)
    ("totaly" "totally" nil 0)
    ("totalyl" "totally" nil 0)
    ("tothe" "to the" nil 0)
    ("towrad" "toward" nil 0)
    ("traditionalyl" "traditionally" nil 0)
    ("transfered" "transferred" nil 0)
    ("truely" "truly" nil 0)
    ("truley" "truly" nil 0)
    ("tryed" "tried" nil 0)
    ("tthe" "the" nil 0)
    ("tub" "tubular" nil 3)
    ("tyhat" "that" nil 0)
    ("tyhe" "the" nil 0)
    ("udnerstand" "understand" nil 0)
    ("understnad" "understand" nil 0)
    ("undert he" "under the" nil 0)
    ("unicode" "Unicode" nil 4)
    ("unitedstates" "United States" nil 0)
    ("unliek" "unlike" nil 0)
    ("unpleasently" "unpleasantly" nil 0)
    ("unregistared" "unregistered" nil 0)
    ("untill" "until" nil 0)
    ("untilll" "until" nil 0)
    ("upd" "UPDATE" nil 1)
    ("useing" "using" nil 0)
    ("usualyl" "usually" nil 0)
    ("val" "VALUES" nil 1)
    ("vender" "vendor" nil 1)
    ("veyr" "very" nil 0)
    ("virtualyl" "virtually" nil 0)
    ("vrey" "very" nil 0)
    ("vulnerible" "vulnerable" nil 0)
    ("waht" "what" nil 1)
    ("warrent" "warrant" nil 0)
    ("wasnt" "wasn't" nil 0)
    ("watn" "want" nil 0)
    ("webc" "Web Communications" nil 0)
    ("wehn" "when" nil 0)
    ("wernt" "weren't" nil 0)
    ("werre" "were" nil 0)
    ("wethee" "whether" nil 0)
    ("wh" "WHERE" nil 9)
    ("whcih" "which" nil 0)
    ("wherre" "where" nil 0)
    ("whic" "which" nil 0)
    ("whihc" "which" nil 0)
    ("whos" "who's" nil 0)
    ("whove" "who've" nil 0)
    ("whta" "what" nil 0)
    ("wief" "wife" nil 0)
    ("wierd" "weird" nil 0)
    ("wihch" "which" nil 0)
    ("wiht" "with" nil 0)
    ("willbe" "will be" nil 0)
    ("windoes" "windows" nil 0)
    ("witha" "with a" nil 0)
    ("withe" "with" nil 0)
    ("witht" "with" nil 1)
    ("withthe" "with the" nil 0)
    ("wiull" "will" nil 0)
    ("wnat" "want" nil 0)
    ("wnated" "wanted" nil 1)
    ("wnats" "wants" nil 0)
    ("woh" "who" nil 0)
    ("wohle" "whole" nil 0)
    ("wokr" "work" nil 0)
    ("woudl" "would" nil 0)
    ("woudln" "wouldn" nil 0)
    ("wouldbe" "would be" nil 0)
    ("wouldnt" "wouldn't" nil 0)
    ("wriet" "write" nil 0)
    ("writting" "writing" nil 0)
    ("wrod" "word" nil 0)
    ("wroet" "wrote" nil 0)
    ("wroking" "working" nil 0)
    ("wtih" "with" nil 0)
    ("wuould" "would" nil 0)
    ("wya" "way" nil 0)
    ("yera" "year" nil 0)
    ("yeras" "years" nil 0)
    ("yersa" "years" nil 0)
    ("yoiu" "you" nil 0)
    ("youare" "you are" nil 0)
    ("youd" "you'd" nil 0)
    ("youre" "you're" nil 0)
    ("youve" "you've" nil 0)
    ("ytou" "you" nil 0)
    ("yuo" "you" nil 0)
    ("yuor" "your" nil 1)
   ))

(define-abbrev-table 'gnus-article-edit-mode-abbrev-table '())

(define-abbrev-table 'gnus-sticky-article-mode-abbrev-table '())

(define-abbrev-table 'google-maps-static-mode-abbrev-table '())

(define-abbrev-table 'grep-mode-abbrev-table '())

(define-abbrev-table 'helm-grep-mode-abbrev-table '())

(define-abbrev-table 'help-mode-abbrev-table '())

(define-abbrev-table 'html-mode-abbrev-table '())

(define-abbrev-table 'identica-update-status-edit-mode-abbrev-table '())

(define-abbrev-table 'idl-mode-abbrev-table '())

(define-abbrev-table 'image-dired-display-image-mode-abbrev-table '())

(define-abbrev-table 'image-dired-thumbnail-mode-abbrev-table '())

(define-abbrev-table 'inferior-moz-mode-abbrev-table '())

(define-abbrev-table 'inferior-php-mode-abbrev-table
  '(
    ("8e" "\\n\";" nil 0)
    ("8o" "$output .= \"" nil 0)
   ))

(define-abbrev-table 'inferior-python-mode-abbrev-table '())

(define-abbrev-table 'internal-ange-ftp-mode-abbrev-table '())

(define-abbrev-table 'ipa-mode-abbrev-table '())

(define-abbrev-table 'jabber-console-mode-abbrev-table '())

(define-abbrev-table 'java-mode-abbrev-table
  '(
   ))

(define-abbrev-table 'jde-mode-abbrev-table '())

(define-abbrev-table 'jde-run-mode-abbrev-table '())

(define-abbrev-table 'js-mode-abbrev-table '())

(define-abbrev-table 'js2-mode-abbrev-table '())

(define-abbrev-table 'jython-mode-abbrev-table '())

(define-abbrev-table 'latex-mode-abbrev-table '())

(define-abbrev-table 'lisp-interaction-mode-abbrev-table '())

(define-abbrev-table 'lisp-mode-abbrev-table '())

(define-abbrev-table 'log-edit-mode-abbrev-table '())

(define-abbrev-table 'magit-branch-manager-mode-abbrev-table '())

(define-abbrev-table 'magit-commit-mode-abbrev-table '())

(define-abbrev-table 'magit-diff-mode-abbrev-table '())

(define-abbrev-table 'magit-log-edit-mode-abbrev-table '())

(define-abbrev-table 'magit-log-mode-abbrev-table '())

(define-abbrev-table 'magit-reflog-mode-abbrev-table '())

(define-abbrev-table 'magit-show-branches-mode-abbrev-table '())

(define-abbrev-table 'magit-stash-mode-abbrev-table '())

(define-abbrev-table 'magit-status-mode-abbrev-table '())

(define-abbrev-table 'magit-wazzup-mode-abbrev-table '())

(define-abbrev-table 'makefile-automake-mode-abbrev-table '())

(define-abbrev-table 'makefile-bsdmake-mode-abbrev-table '())

(define-abbrev-table 'makefile-gmake-mode-abbrev-table '())

(define-abbrev-table 'makefile-imake-mode-abbrev-table '())

(define-abbrev-table 'makefile-makepp-mode-abbrev-table '())

(define-abbrev-table 'makefile-mode-abbrev-table '())

(define-abbrev-table 'markdown-mode-abbrev-table '())

(define-abbrev-table 'message-mode-abbrev-table '())

(define-abbrev-table 'mumamo-border-mode-abbrev-table '())

(define-abbrev-table 'mumamo-comment-mode-abbrev-table '())

(define-abbrev-table 'noshell-process-mode-abbrev-table '())

(define-abbrev-table 'nroff-mode-abbrev-table '())

(define-abbrev-table 'nxhtml-genshi-mode-abbrev-table '())

(define-abbrev-table 'nxhtml-mjt-mode-abbrev-table '())

(define-abbrev-table 'nxhtml-mode-abbrev-table '())

(define-abbrev-table 'nxml-mode-abbrev-table '())

(define-abbrev-table 'objc-mode-abbrev-table
  '(
   ))

(define-abbrev-table 'occur-edit-mode-abbrev-table '())

(define-abbrev-table 'occur-mode-abbrev-table '())

(define-abbrev-table 'org-export-stack-mode-abbrev-table '())

(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("8c" "Comment: Damon Haley
" nil 3)
    ("8m" "#+begin_src emacs-lisp

(message \"0 dkh-file... Done\")

#+end_src" nil 1)
    ("bl" "#+begin_src emacs-lisp" nil 315)
    ("bp" "#+begin_src php
#+end_src" nil 4)
    ("el" "#+end_src" nil 319)
    ("ol" "#+begin_src emacs-lisp

(message (concat \"0 \" (buffer-name) \"... Done\"))
#+end_src" nil 19)
    ("sblk" "" skel-org-block 0)
    ("sbp" "#+begin_src php

#+end_src" nil 4)
    ("sditaa" "" skel-org-block-ditaa 0)
    ("sdot" "" skel-org-block-dot 0)
    ("selisp" "" skel-org-block-elisp 0)
    ("splantuml" "" skel-org-block-plantuml 0)
   ))

(define-abbrev-table 'outline-mode-abbrev-table '())

(define-abbrev-table 'package-menu-mode-abbrev-table '())

(define-abbrev-table 'pandoc-@-mode-abbrev-table '())

(define-abbrev-table 'perl-mode-abbrev-table '())

(define-abbrev-table 'php+-mode-abbrev-table '())

(define-abbrev-table 'php-mode-abbrev-table
  '(
    ("8e" "\\n\";" nil 4)
    ("8o" "$output .= \"" nil 4)
    ("ex" "extends" nil 0)
   ))

(define-abbrev-table 'pike-mode-abbrev-table
  '(
   ))

(define-abbrev-table 'plain-tex-mode-abbrev-table '())

(define-abbrev-table 'plstore-mode-abbrev-table '())

(define-abbrev-table 'proced-mode-abbrev-table '())

(define-abbrev-table 'process-menu-mode-abbrev-table '())

(define-abbrev-table 'prog-mode-abbrev-table '())

(define-abbrev-table 'python-mode-abbrev-table '())

(define-abbrev-table 'reb-lisp-mode-abbrev-table '())

(define-abbrev-table 'reb-mode-abbrev-table '())

(define-abbrev-table 'rebase-mode-abbrev-table '())

(define-abbrev-table 'rst-mode-abbrev-table '())

(define-abbrev-table 'rst-toc-mode-abbrev-table '())

(define-abbrev-table 'ruby-mode-abbrev-table '())

(define-abbrev-table 'sauron-mode-abbrev-table '())

(define-abbrev-table 'scheme-mode-abbrev-table '())

(define-abbrev-table 'secrets-mode-abbrev-table '())

(define-abbrev-table 'select-tags-table-mode-abbrev-table '())

(define-abbrev-table 'sgml-mode-abbrev-table '())

(define-abbrev-table 'sh-mode-abbrev-table '())

(define-abbrev-table 'shell-mode-abbrev-table '())

(define-abbrev-table 'sieve-mode-abbrev-table '())

(define-abbrev-table 'slitex-mode-abbrev-table '())

(define-abbrev-table 'smime-mode-abbrev-table '())

(define-abbrev-table 'snippet-mode-abbrev-table '())

(define-abbrev-table 'special-mode-abbrev-table '())

(define-abbrev-table 'speedbar-mode-abbrev-table '())

(define-abbrev-table 'sql-mode-abbrev-table
  '(
    ("absolute" "ABSOLUTE" nil 1)
    ("action" "ACTION" nil 1)
    ("add" "ADD" nil 1)
    ("after" "AFTER" nil 1)
    ("all" "ALL" nil 1)
    ("allocate" "ALLOCATE" nil 1)
    ("alter" "ALTER" nil 1)
    ("and" "AND" nil 1)
    ("any" "ANY" nil 1)
    ("are" "ARE" nil 1)
    ("array" "ARRAY" nil 1)
    ("as" "AS" nil 1)
    ("asc" "ASC" nil 1)
    ("asensitive" "ASENSITIVE" nil 1)
    ("assertion" "ASSERTION" nil 1)
    ("asymmetric" "ASYMMETRIC" nil 1)
    ("at" "AT" nil 1)
    ("atomic" "ATOMIC" nil 1)
    ("authorization" "AUTHORIZATION" nil 1)
    ("avg" "AVG" nil 1)
    ("before" "BEFORE" nil 1)
    ("begin" "BEGIN" nil 1)
    ("between" "BETWEEN" nil 1)
    ("bigint" "BIGINT" nil 1)
    ("binary" "BINARY" nil 1)
    ("bit" "BIT" nil 1)
    ("bitlength" "BITLENGTH" nil 1)
    ("blob" "BLOB" nil 1)
    ("boolean" "BOOLEAN" nil 1)
    ("both" "BOTH" nil 1)
    ("breadth" "BREADTH" nil 1)
    ("by" "BY" nil 1)
    ("call" "CALL" nil 1)
    ("called" "CALLED" nil 1)
    ("cascade" "CASCADE" nil 1)
    ("cascaded" "CASCADED" nil 1)
    ("case" "CASE" nil 1)
    ("cast" "CAST" nil 1)
    ("catalog" "CATALOG" nil 1)
    ("char" "CHAR" nil 1)
    ("char_length" "CHAR_LENGTH" nil 1)
    ("character" "CHARACTER" nil 1)
    ("character_length" "CHARACTER_LENGTH" nil 1)
    ("check" "CHECK" nil 1)
    ("clob" "CLOB" nil 1)
    ("close" "CLOSE" nil 1)
    ("coalesce" "COALESCE" nil 1)
    ("collate" "COLLATE" nil 1)
    ("collation" "COLLATION" nil 1)
    ("column" "COLUMN" nil 1)
    ("commit" "COMMIT" nil 1)
    ("condition" "CONDITION" nil 1)
    ("connect" "CONNECT" nil 1)
    ("connection" "CONNECTION" nil 1)
    ("constraint" "CONSTRAINT" nil 1)
    ("constraints" "CONSTRAINTS" nil 1)
    ("constructor" "CONSTRUCTOR" nil 1)
    ("contains" "CONTAINS" nil 1)
    ("continue" "CONTINUE" nil 1)
    ("convert" "CONVERT" nil 1)
    ("corresponding" "CORRESPONDING" nil 1)
    ("count" "COUNT" nil 1)
    ("create" "CREATE" nil 1)
    ("cross" "CROSS" nil 1)
    ("cube" "CUBE" nil 1)
    ("current" "CURRENT" nil 1)
    ("current_date" "CURRENT_DATE" nil 1)
    ("current_default_transform_group" "CURRENT_DEFAULT_TRANSFORM_GROUP" nil 1)
    ("current_path" "CURRENT_PATH" nil 1)
    ("current_role" "CURRENT_ROLE" nil 1)
    ("current_time" "CURRENT_TIME" nil 1)
    ("current_timestamp" "CURRENT_TIMESTAMP" nil 1)
    ("current_transform_group_for_type" "CURRENT_TRANSFORM_GROUP_FOR_TYPE" nil 1)
    ("current_user" "CURRENT_USER" nil 1)
    ("cursor" "CURSOR" nil 1)
    ("cycle" "CYCLE" nil 1)
    ("data" "DATA" nil 1)
    ("date" "DATE" nil 1)
    ("day" "DAY" nil 1)
    ("deallocate" "DEALLOCATE" nil 1)
    ("dec" "DEC" nil 1)
    ("decimal" "DECIMAL" nil 1)
    ("declare" "DECLARE" nil 1)
    ("default" "DEFAULT" nil 1)
    ("deferrable" "DEFERRABLE" nil 1)
    ("deferred" "DEFERRED" nil 1)
    ("delete" "DELETE" nil 1)
    ("depth" "DEPTH" nil 1)
    ("deref" "DEREF" nil 1)
    ("desc" "DESC" nil 1)
    ("describe" "DESCRIBE" nil 1)
    ("descriptor" "DESCRIPTOR" nil 1)
    ("deterministic" "DETERMINISTIC" nil 1)
    ("diagnostics" "DIAGNOSTICS" nil 1)
    ("disconnect" "DISCONNECT" nil 1)
    ("distinct" "DISTINCT" nil 1)
    ("do" "DO" nil 1)
    ("domain" "DOMAIN" nil 1)
    ("double" "DOUBLE" nil 1)
    ("drop" "DROP" nil 1)
    ("dynamic" "DYNAMIC" nil 1)
    ("each" "EACH" nil 1)
    ("element" "ELEMENT" nil 1)
    ("else" "ELSE" nil 1)
    ("elseif" "ELSEIF" nil 1)
    ("end" "END" nil 1)
    ("equals" "EQUALS" nil 1)
    ("escape" "ESCAPE" nil 1)
    ("except" "EXCEPT" nil 1)
    ("exception" "EXCEPTION" nil 1)
    ("exec" "EXEC" nil 1)
    ("execute" "EXECUTE" nil 1)
    ("exists" "EXISTS" nil 1)
    ("exit" "EXIT" nil 1)
    ("external" "EXTERNAL" nil 1)
    ("extract" "EXTRACT" nil 1)
    ("false" "FALSE" nil 1)
    ("fetch" "FETCH" nil 1)
    ("filter" "FILTER" nil 1)
    ("first" "FIRST" nil 1)
    ("float" "FLOAT" nil 1)
    ("for" "FOR" nil 1)
    ("foreign" "FOREIGN" nil 1)
    ("found" "FOUND" nil 1)
    ("free" "FREE" nil 1)
    ("from" "FROM" nil 1)
    ("full" "FULL" nil 1)
    ("function" "FUNCTION" nil 1)
    ("general" "GENERAL" nil 1)
    ("get" "GET" nil 1)
    ("global" "GLOBAL" nil 1)
    ("go" "GO" nil 1)
    ("goto" "GOTO" nil 1)
    ("grant" "GRANT" nil 1)
    ("group" "GROUP" nil 1)
    ("grouping" "GROUPING" nil 1)
    ("handler" "HANDLER" nil 1)
    ("having" "HAVING" nil 1)
    ("hold" "HOLD" nil 1)
    ("hour" "HOUR" nil 1)
    ("identity" "IDENTITY" nil 1)
    ("if" "IF" nil 1)
    ("immediate" "IMMEDIATE" nil 1)
    ("in" "IN" nil 1)
    ("indicator" "INDICATOR" nil 1)
    ("initially" "INITIALLY" nil 1)
    ("inner" "INNER" nil 1)
    ("inout" "INOUT" nil 1)
    ("input" "INPUT" nil 1)
    ("insensitive" "INSENSITIVE" nil 1)
    ("insert" "INSERT" nil 1)
    ("int" "INT" nil 1)
    ("integer" "INTEGER" nil 1)
    ("intersect" "INTERSECT" nil 1)
    ("interval" "INTERVAL" nil 1)
    ("into" "INTO" nil 1)
    ("is" "IS" nil 1)
    ("isolation" "ISOLATION" nil 1)
    ("iterate" "ITERATE" nil 1)
    ("join" "JOIN" nil 1)
    ("key" "KEY" nil 1)
    ("language" "LANGUAGE" nil 1)
    ("large" "LARGE" nil 1)
    ("last" "LAST" nil 1)
    ("lateral" "LATERAL" nil 1)
    ("leading" "LEADING" nil 1)
    ("leave" "LEAVE" nil 1)
    ("left" "LEFT" nil 1)
    ("level" "LEVEL" nil 1)
    ("like" "LIKE" nil 1)
    ("local" "LOCAL" nil 1)
    ("localtime" "LOCALTIME" nil 1)
    ("localtimestamp" "LOCALTIMESTAMP" nil 1)
    ("locator" "LOCATOR" nil 1)
    ("loop" "LOOP" nil 1)
    ("lower" "LOWER" nil 1)
    ("map" "MAP" nil 1)
    ("match" "MATCH" nil 1)
    ("member" "MEMBER" nil 1)
    ("merge" "MERGE" nil 1)
    ("method" "METHOD" nil 1)
    ("min" "MIN" nil 1)
    ("minute" "MINUTE" nil 1)
    ("modifies" "MODIFIES" nil 1)
    ("module" "MODULE" nil 1)
    ("month" "MONTH" nil 1)
    ("multiset" "MULTISET" nil 1)
    ("names" "NAMES" nil 1)
    ("national" "NATIONAL" nil 1)
    ("natural" "NATURAL" nil 1)
    ("nchar" "NCHAR" nil 1)
    ("nclob" "NCLOB" nil 1)
    ("new" "NEW" nil 1)
    ("next" "NEXT" nil 1)
    ("no" "NO" nil 1)
    ("none" "NONE" nil 1)
    ("not" "NOT" nil 1)
    ("null" "NULL" nil 1)
    ("nullif" "NULLIF" nil 1)
    ("numeric" "NUMERIC" nil 1)
    ("object" "OBJECT" nil 1)
    ("octet_length" "OCTET_LENGTH" nil 1)
    ("of" "OF" nil 1)
    ("old" "OLD" nil 1)
    ("on" "ON" nil 1)
    ("only" "ONLY" nil 1)
    ("open" "OPEN" nil 1)
    ("option" "OPTION" nil 1)
    ("or" "OR" nil 1)
    ("order" "ORDER" nil 1)
    ("ordinality" "ORDINALITY" nil 1)
    ("out" "OUT" nil 1)
    ("outer" "OUTER" nil 1)
    ("output" "OUTPUT" nil 1)
    ("over" "OVER" nil 1)
    ("overlaps" "OVERLAPS" nil 1)
    ("pad" "PAD" nil 1)
    ("parameter" "PARAMETER" nil 1)
    ("partial" "PARTIAL" nil 1)
    ("partition" "PARTITION" nil 1)
    ("path" "PATH" nil 1)
    ("position" "POSITION" nil 1)
    ("precision" "PRECISION" nil 1)
    ("prepare" "PREPARE" nil 1)
    ("preserve" "PRESERVE" nil 1)
    ("primary" "PRIMARY" nil 1)
    ("prior" "PRIOR" nil 1)
    ("privileges" "PRIVILEGES" nil 1)
    ("procedure" "PROCEDURE" nil 1)
    ("public" "PUBLIC" nil 1)
    ("range" "RANGE" nil 1)
    ("read" "READ" nil 1)
    ("reads" "READS" nil 1)
    ("real" "REAL" nil 1)
    ("recursive" "RECURSIVE" nil 1)
    ("ref" "REF" nil 1)
    ("references" "REFERENCES" nil 1)
    ("referencing" "REFERENCING" nil 1)
    ("relative" "RELATIVE" nil 1)
    ("release" "RELEASE" nil 1)
    ("repeat" "REPEAT" nil 1)
    ("resignal" "RESIGNAL" nil 1)
    ("restrict" "RESTRICT" nil 1)
    ("result" "RESULT" nil 1)
    ("return" "RETURN" nil 1)
    ("returns" "RETURNS" nil 1)
    ("revoke" "REVOKE" nil 1)
    ("right" "RIGHT" nil 1)
    ("role" "ROLE" nil 1)
    ("rollback" "ROLLBACK" nil 1)
    ("rollup" "ROLLUP" nil 1)
    ("routine" "ROUTINE" nil 1)
    ("row" "ROW" nil 1)
    ("rows" "ROWS" nil 1)
    ("savepoint" "SAVEPOINT" nil 1)
    ("schema" "SCHEMA" nil 1)
    ("scope" "SCOPE" nil 1)
    ("scroll" "SCROLL" nil 1)
    ("search" "SEARCH" nil 1)
    ("second" "SECOND" nil 1)
    ("section" "SECTION" nil 1)
    ("select" "SELECT" nil 1)
    ("sensitive" "SENSITIVE" nil 1)
    ("session" "SESSION" nil 1)
    ("session_user" "SESSION_USER" nil 1)
    ("set" "SET" nil 1)
    ("sets" "SETS" nil 1)
    ("signal" "SIGNAL" nil 1)
    ("similar" "SIMILAR" nil 1)
    ("size" "SIZE" nil 1)
    ("smallint" "SMALLINT" nil 1)
    ("some" "SOME" nil 1)
    ("space" "SPACE" nil 1)
    ("specific" "SPECIFIC" nil 1)
    ("specifictype" "SPECIFICTYPE" nil 1)
    ("sql" "SQL" nil 1)
    ("sqlcode" "SQLCODE" nil 1)
    ("sqlerror" "SQLERROR" nil 1)
    ("sqlexception" "SQLEXCEPTION" nil 1)
    ("sqlstate" "SQLSTATE" nil 1)
    ("sqlwarning" "SQLWARNING" nil 1)
    ("start" "START" nil 1)
    ("state" "STATE" nil 1)
    ("static" "STATIC" nil 1)
    ("submultiset" "SUBMULTISET" nil 1)
    ("substring" "SUBSTRING" nil 1)
    ("sum" "SUM" nil 1)
    ("symmetric" "SYMMETRIC" nil 1)
    ("system" "SYSTEM" nil 1)
    ("system_user" "SYSTEM_USER" nil 1)
    ("table" "TABLE" nil 1)
    ("tablesample" "TABLESAMPLE" nil 1)
    ("temporary" "TEMPORARY" nil 1)
    ("then" "THEN" nil 1)
    ("time" "TIME" nil 1)
    ("timestamp" "TIMESTAMP" nil 1)
    ("timezone_hour" "TIMEZONE_HOUR" nil 1)
    ("timezone_minute" "TIMEZONE_MINUTE" nil 1)
    ("to" "TO" nil 1)
    ("trailing" "TRAILING" nil 1)
    ("transaction" "TRANSACTION" nil 1)
    ("translate" "TRANSLATE" nil 1)
    ("translation" "TRANSLATION" nil 1)
    ("treat" "TREAT" nil 1)
    ("trigger" "TRIGGER" nil 1)
    ("trim" "TRIM" nil 1)
    ("true" "TRUE" nil 1)
    ("under" "UNDER" nil 1)
    ("undo" "UNDO" nil 1)
    ("union" "UNION" nil 1)
    ("unique" "UNIQUE" nil 1)
    ("unknown" "UNKNOWN" nil 1)
    ("unnest" "UNNEST" nil 1)
    ("until" "UNTIL" nil 1)
    ("update" "UPDATE" nil 1)
    ("upper" "UPPER" nil 1)
    ("usage" "USAGE" nil 1)
    ("user" "USER" nil 1)
    ("using" "USING" nil 1)
    ("value" "VALUE" nil 1)
    ("values" "VALUES" nil 1)
    ("varchar" "VARCHAR" nil 1)
    ("varying" "VARYING" nil 1)
    ("view" "VIEW" nil 1)
    ("when" "WHEN" nil 1)
    ("whenever" "WHENEVER" nil 1)
    ("where" "WHERE" nil 1)
    ("while" "WHILE" nil 1)
    ("window" "WINDOW" nil 1)
    ("with" "WITH" nil 1)
    ("within" "WITHIN" nil 1)
    ("without" "WITHOUT" nil 1)
    ("work" "WORK" nil 1)
    ("write" "WRITE" nil 1)
    ("year" "YEAR" nil 1)
    ("zone" "ZONE" nil 1)
   ))

(define-abbrev-table 'svn-log-edit-mode-abbrev-table '())

(define-abbrev-table 'svn-log-view-mode-abbrev-table '())

(define-abbrev-table 'svn-status-diff-mode-abbrev-table '())

(define-abbrev-table 'synonyms-mode-abbrev-table '())

(define-abbrev-table 'tabulated-list-mode-abbrev-table '())

(define-abbrev-table 'tags-history-mode-abbrev-table '())

(define-abbrev-table 'tar-mode-abbrev-table '())

(define-abbrev-table 'term-mode-abbrev-table '())

(define-abbrev-table 'tex-mode-abbrev-table '())

(define-abbrev-table 'tex-shell-abbrev-table '())

(define-abbrev-table 'text-mode-abbrev-table
  '(
    (";drupal" "💧" nil 0)
    ("^2" "²" nil 0)
    ("^3" "³" nil 0)
    ("almost0" "≈" nil 0)
    ("alpha0" "α" nil 0)
    ("anger_symbol" "💢" nil 0)
    ("angry_face" "😠" nil 0)
    ("anguished_face" "😧" nil 0)
    ("animals" "🐭 🐮 🐍 🐵 🐞" nil 0)
    ("any0" "∀" nil 0)
    ("app" "application" nil 4)
    ("apps" "applications" nil 1)
    ("astonished_face" "😲" nil 0)
    ("athletic_shoe" "👟" nil 0)
    ("baby" "👶" nil 0)
    ("baby_angel" "👼" nil 0)
    ("bbq" "barbecue" nil 3)
    ("beating_heart" "💓" nil 0)
    ("beta0" "β" nil 0)
    ("bikini" "👙" nil 0)
    ("blue_heart" "💙" nil 0)
    ("bookm" "bookmarks" nil 0)
    ("boy" "👦" nil 0)
    ("bride_with_veil" "👰" nil 0)
    ("briefcase" "💼" nil 0)
    ("broken_heart" "💔" nil 0)
    ("bust_in_silhouette" "👤" nil 0)
    ("busts_in_silhouette" "👥" nil 0)
    ("c0" "©" nil 0)
    ("cat" "😸" nil 0)
    ("cat_face_with_tears_of_joy" "😹" nil 0)
    ("cat_face_with_wry_smile" "😼" nil 0)
    ("chi" "Chisya" nil 0)
    ("clapping_hands_sign" "👏" nil 0)
    ("closed_umbrella" "🌂" nil 0)
    ("collision_symbol" "💥" nil 0)
    ("confounded_face" "😖" nil 0)
    ("confused_face" "😕" nil 0)
    ("construction_worker" "👷" nil 0)
    ("couple_with_heart" "💑" nil 0)
    ("crown" "👑" nil 0)
    ("crying_cat_face" "😿" nil 0)
    ("crying_face" "😢" nil 0)
    ("da" "Damon" nil 2)
    ("dancer" "💃" nil 0)
    ("dash_symbol" "💨" nil 0)
    ("def" "definitely" nil 0)
    ("deg0" "℃" nil 0)
    ("delta0" "δ" nil 0)
    ("dir" "directory" nil 4)
    ("disappointed_but_relieved_face" "😥" nil 0)
    ("disappointed_face" "😞" nil 0)
    ("dizzy_face" "😵" nil 0)
    ("dizzy_symbol" "💫" nil 0)
    ("dress" "👗" nil 0)
    ("droplet" "💧" nil 0)
    ("ear" "👂" nil 0)
    ("elm0" "∈" nil 0)
    ("epsilon0" "ε" nil 0)
    ("eta0" "η" nil 0)
    ("expressionless_face" "😑" nil 0)
    ("extraterrestrial_alien" "👽" nil 0)
    ("eyeglasses" "👓" nil 0)
    ("eyes" "👀" nil 0)
    ("face_massage" "💆" nil 0)
    ("face_savouring_delicious_food" "😋" nil 0)
    ("face_screaming in_fear" "😱" nil 0)
    ("face_throwing_a_kiss" "😘" nil 0)
    ("face_with_cold_sweat" "😓" nil 0)
    ("face_with_look_of_triumph" "😤" nil 0)
    ("face_with_medical_mask" "😷" nil 0)
    ("face_with_no_good_gesture" "🙅" nil 0)
    ("face_with_ok_gesture" "🙆" nil 0)
    ("face_with_open_mouth" "😮" nil 0)
    ("face_with_open_mouth_and_cold_sweat" "😰" nil 0)
    ("face_with_stuck-out_tongue" "😛" nil 0)
    ("face_with_stuck-out_tongue_and_tightly-closed_eyes" "😝" nil 0)
    ("face_with_stuck-out_tongue_and_winking_eye" "😜" nil 0)
    ("face_with_tears_of_joy" "😂" nil 0)
    ("face_without_mouth" "😶" nil 0)
    ("family" "👪" nil 0)
    ("fangs" "😺 😸 😻 😽 😼 🙀 😿 😹 😾" nil 1)
    ("fearful_face" "😨" nil 0)
    ("fil" "file system" nil 0)
    ("fire" "🔥" nil 0)
    ("first quarter moon with face" "🌛" nil 0)
    ("fisted_hand_sign" "👊" nil 0)
    ("flexed_biceps" "💪" nil 0)
    ("flushed_face" "😳" nil 0)
    ("footprints" "👣" nil 0)
    ("frowning_face_with_open_mouth" "😦" nil 0)
    ("full moon with face" "🌝" nil 0)
    ("gem_stone" "💎" nil 0)
    ("girl" "👧" nil 0)
    ("glowing_star" "🌟" nil 0)
    ("greek_small_letter_α" "α" nil 0)
    ("green_heart" "💚" nil 0)
    ("grimacing_face" "😬" nil 0)
    ("grinning_cat_face_with_smiling_eyes" "😸" nil 0)
    ("grinning_face" "😀" nil 0)
    ("grinning_face_with_smiling_eyes" "😁" nil 0)
    ("growing_heart" "💗" nil 0)
    ("guardsman" "💂" nil 0)
    ("haircut" "💇" nil 0)
    ("handbag" "👜" nil 0)
    ("happy_person_raising_one_hand" "🙋" nil 0)
    ("hear-no-evil_monkey" "🙉" nil 0)
    ("heart0" "♥" nil 0)
    ("heart_with_arrow" "💘" nil 0)
    ("hearts" "👼 👶 💝 💛 💕 💖 😍 😻 💞 💜 ❤ 💘 💗 💑 💔 💙 💓" nil 0)
    ("heavy_black_heart" "❤" nil 0)
    ("high-heeled_shoe" "👠" nil 0)
    ("hushed_face" "😯" nil 0)
    ("imp" "👿" nil 0)
    ("inf0" "∞" nil 0)
    ("infinity" "∞" nil 0)
    ("information_desk_person" "💁" nil 0)
    ("int0" "∫" nil 0)
    ("japanese_goblin" "👺" nil 0)
    ("japanese_ogre" "👹" nil 0)
    ("jdoll" "🎎" nil 1)
    ("jeans" "👖" nil 0)
    ("kimono" "👘" nil 0)
    ("kiss" "💏" nil 0)
    ("kiss_mark" "💋" nil 0)
    ("kissing_cat_face_with_closed_eyes" "😽" nil 0)
    ("kissing_face" "😗" nil 0)
    ("kissing_face_with_closed_eyes" "😚" nil 0)
    ("kissing_face_with_smiling_eyes" "😙" nil 0)
    ("last quarter moon with face" "🌜" nil 0)
    ("lipstick" "💄" nil 0)
    ("loudly_crying_face" "😭" nil 0)
    ("love_hotel" "🏩" nil 0)
    ("love_letter" "💌" nil 0)
    ("maint" "maintenance" nil 1)
    ("man" "👨" nil 2)
    ("man_and_woman_holding_hands" "👫" nil 0)
    ("man_with_gua_pi_mao" "👲" nil 0)
    ("man_with_turban" "👳" nil 0)
    ("mans_shoe" "👞" nil 0)
    ("mig" "migrated" nil 0)
    ("moons" "🌚 🌛 🌜🌝" nil 1)
    ("mouth" "👄" nil 0)
    ("nail_polish" "💅" nil 0)
    ("necktie" "👔" nil 0)
    ("neutral_face" "😐" nil 0)
    ("new moon with face" "🌚" nil 0)
    ("nose" "👃" nil 0)
    ("notis0" "≠" nil 0)
    ("ok_hand_sign" "👌" nil 0)
    ("older_man" "👴" nil 0)
    ("older_woman" "👵" nil 0)
    ("open_hands_sign" "👐" nil 0)
    ("pedestrian" "🚶" nil 0)
    ("pensive_face" "😔" nil 0)
    ("persevering_face" "😣" nil 0)
    ("person_bowing_deeply" "🙇" nil 0)
    ("person_frowning" "🙍" nil 0)
    ("person_raising_both_hands_in_celebration" "🙌" nil 0)
    ("person_with_blond_hair" "👱" nil 0)
    ("person_with_folded_hands" "🙏" nil 0)
    ("person_with_pouting_face" "🙎" nil 0)
    ("pile of poo" "💩" nil 0)
    ("pine" "🎍" nil 0)
    ("police_officer" "👮" nil 0)
    ("poo" "💩" nil 0)
    ("pouch" "👝" nil 0)
    ("pouting_cat_face" "😾" nil 0)
    ("pouting_face" "😡" nil 0)
    ("princess" "👸" nil 0)
    ("privs" "privileges" nil 1)
    ("purple_heart" "💜" nil 0)
    ("purse" "👛" nil 0)
    ("question" "🙋" nil 0)
    ("raised_fist" "✊" nil 0)
    ("raised_hand" "✋" nil 0)
    ("rec" "recommend" nil 1)
    ("rel" "relevant" nil 0)
    ("relieved_face" "😌" nil 0)
    ("revolving_hearts" "💞" nil 0)
    ("rheart" "💝" nil 0)
    ("rho0" "ρ" nil 3)
    ("ribbon" "🎀" nil 0)
    ("ring" "💍" nil 0)
    ("runner" "🏃" nil 0)
    ("running_shirt_with_sash" "🎽" nil 0)
    ("see-no-evil_monkey" "🙈" nil 0)
    ("skull" "💀" nil 0)
    ("sleeping_face" "😴" nil 0)
    ("sleeping_symbol" "💤" nil 0)
    ("sleepy_face" "😪" nil 0)
    ("smiling_cat_face_with_heart-shaped_eyes" "😻" nil 0)
    ("smiling_cat_face_with_open_mouth" "😺" nil 0)
    ("smiling_face_with_halo" "😇" nil 0)
    ("smiling_face_with_heart-shaped_eyes" "😍" nil 0)
    ("smiling_face_with_horns" "😈" nil 0)
    ("smiling_face_with_open_mouth" "😃" nil 0)
    ("smiling_face_with_open_mouth_and_cold_sweat" "😅" nil 0)
    ("smiling_face_with_open_mouth_and_smiling_eyes" "😄" nil 0)
    ("smiling_face_with_open_mouth_and_tightly-closed_eyes" "😆" nil 0)
    ("smiling_face_with_smiling_eyes" "😊" nil 0)
    ("smiling_face_with_sunglasses" "😎" nil 0)
    ("smirking_face" "😏" nil 0)
    ("sparkles" "✨" nil 0)
    ("sparkling_heart" "💖" nil 0)
    ("speak-no-evil_monkey" "🙊" nil 0)
    ("speech_balloon" "💬" nil 0)
    ("splashing_sweet_symbol" "💦" nil 0)
    ("suff" "sufficient" nil 0)
    ("t-shirt" "👕" nil 0)
    ("thnx" "Thanks and let me know if you have any questions." nil 3)
    ("thought_balloon" "💭" nil 0)
    ("thumbs_ up_sign" "👍" nil 0)
    ("thumbs_down_sign" "👎" nil 0)
    ("tib" "This is because" nil 0)
    ("tired_face" "😫" nil 0)
    ("tongue" "👅" nil 0)
    ("top_hat" "🎩" nil 0)
    ("two_hearts" "💕" nil 0)
    ("two_men_holding_hands" "👬" nil 0)
    ("two_women_holding_hands" "👭" nil 0)
    ("unamused_face" "😒" nil 0)
    ("unf" "unfortunately" nil 1)
    ("victory_hand" "✌" nil 0)
    ("waving_hand_sign" "👋" nil 0)
    ("weary_cat_face" "🙀" nil 0)
    ("weary_face" "😩" _nil 0)
    ("white_down_pointing_backhand_index" "👇" nil 0)
    ("white_left_pointing_backhand_index" "👈" nil 0)
    ("white_right_pointing_backhand_index" "👉" nil 0)
    ("white_smiling_face" "☺" nil 0)
    ("white_up_pointing_backhand_index" "👆" nil 0)
    ("white_up_pointing_index" "☝" nil 0)
    ("winking_face" "😉" nil 0)
    ("woman" "👩" nil 1)
    ("woman_with_bunny_ears" "👯" nil 0)
    ("womans_boots" "👢" nil 0)
    ("womans_clothes" "👚" nil 0)
    ("womans_hat" "👒" nil 0)
    ("womans_sandal" "👡" nil 0)
    ("worried_face" "😟" nil 0)
    ("wygac" "when you get a chance" nil 0)
    ("yellow_heart" "💛" nil 0)
    ("yest" "yesterday" nil 0)
   ))

(define-abbrev-table 'tla-changelog-mode-abbrev-table '())

(define-abbrev-table 'tla-log-edit-mode-abbrev-table '())

(define-abbrev-table 'tla-revision-list-mode-abbrev-table '())

(define-abbrev-table 'tla-tree-lint-mode-abbrev-table '())

(define-abbrev-table 'twittering-edit-mode-abbrev-table '())

(define-abbrev-table 'udev-control-mode-abbrev-table '())

(define-abbrev-table 'vc-annotate-mode-abbrev-table '())

(define-abbrev-table 'vc-bzr-log-view-mode-abbrev-table '())

(define-abbrev-table 'vc-dir-mode-abbrev-table '())

(define-abbrev-table 'vc-git-log-edit-mode-abbrev-table '())

(define-abbrev-table 'vc-git-log-view-mode-abbrev-table '())

(define-abbrev-table 'vc-hg-log-view-mode-abbrev-table '())

(define-abbrev-table 'vc-mtn-log-view-mode-abbrev-table '())

(define-abbrev-table 'vc-svn-log-view-mode-abbrev-table '())

(define-abbrev-table 'wab-compilation-mode-abbrev-table '())

(define-abbrev-table 'web-vcs-investigate-output-mode-abbrev-table '())

(define-abbrev-table 'xah-html-mode-abbrev-table '())

(define-abbrev-table 'xah-html6-mode-abbrev-table '())

(define-abbrev-table 'xgit-annotate-mode-abbrev-table '())

(define-abbrev-table 'xgit-changelog-mode-abbrev-table '())

(define-abbrev-table 'xgit-diff-mode-abbrev-table '())

(define-abbrev-table 'xmtn-conflicts-mode-abbrev-table '())

(define-abbrev-table 'xmtn-log-edit-mode-abbrev-table '())

(define-abbrev-table 'yaml-mode-abbrev-table '())

