(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(diff-added ((t (:foreground "DarkGreen"))))
 '(diff-added2 ((t (:foreground "SeaGreen"))))
 '(diff-changed ((t (:foreground "MediumBlue"))))
 '(diff-context ((t (:foreground "Black"))))
 '(diff-file-header ((t (:background "grey90" :foreground "Red"))))
 '(diff-header ((t (:background "grey85" :foreground "red"))))
 '(diff-hunk-header ((t (:background "grey90" :foreground "black"))))
 '(diff-index ((t (:foreground "Green"))))
 '(diff-nonexistent ((t (:foreground "DarkBlue"))))
 '(diff-removed ((t (:foreground "firebrick"))))
 '(diff-removed2 ((t (:foreground "Orange"))))
 '(font-lock-comment-face ((((class color)) (:foreground "firebrick"))))
 '(helm-M-x-key ((t (:foreground "dark red" :underline t))))
 '(helm-candidate-number ((t (:background "#faffb5" :foreground "black"))))
 '(helm-selection ((t (:background "#b5ffd1" :underline t))))
 '(helm-separator ((t (:foreground "#ffbfb5"))))
 '(helm-source-header ((t (:background "#abd7f0" :foreground "black" :underline t))))
 '(helm-visible-mark ((t (:background "#d1f5ae"))))
 '(hl-line ((t (:background "cornsilk"))))
 '(ledger-register-pending-face ((t (:weight bold))))
 '(linum ((t (:foreground "blue"))))
 '(lusty-match-face ((t (:inherit helm-match))))
 '(magit-branch-face ((((class color) (background light)) (:foreground "Blue"))))
 '(magit-diff-none-face ((((class color) (background light)) (:foreground "grey50"))))
 '(magit-header ((t (:weight bold))))
 '(magit-topgit-current ((t nil)))
 '(match ((t (:background "light cyan"))))
 '(slime-highlight-edits-face ((((class color) (background light)) (:background "gray98"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "light salmon"))))
 '(whitespace-line ((t (:background "lemon chiffon" :foreground "dark violet")))
 '(default ((t (:inherit nil :stipple nil :background "#002b36" :foreground "#657b83" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "apple" :family "Anonymous_Pro"))))
 '(comint-highlight-input ((t (:foreground "#2aa198"))))
 '(comint-highlight-prompt ((((min-colors 88) (background dark)) (:foreground "#268bd2"))))
 '(cursor ((t (:background "#FFFFAA" :foreground "#222222"))))
 '(custom-button ((((type x w32 ns) (class color)) (:background "#073642" :foreground "#93a1a1" :box (:line-width 2 :color "#073642" :style released-button)))))
 '(custom-button-mouse ((((type x w32 ns) (class color)) (:background "#586e75" :foreground "#93a1a1" :box (:line-width 2 :style released-button)))))
 '(custom-button-pressed ((((type x w32 ns) (class color)) (:background "#586e75" :foreground "#93a1a1" :box (:line-width 2 :style pressed-button)))))
 '(custom-state ((((class color) (background dark)) (:foreground "#859900"))))
 '(custom-visibility ((t (:inherit link))))
 '(erc-action-face ((t (:inherit erc-default-face :foreground "#6c71c4" :weight bold))))
 '(erc-bold-face ((t (:inherit erc-default-face :weight bold))))
 '(erc-capab-identify-unidentified ((t (:inherit erc-default-face))))
 '(erc-command-indicator-face ((t (:inherit erc-default-face :weight bold))))
 '(erc-current-nick-face ((t (:inherit erc-default-face :foreground "DarkTurquoise" :weight bold))))
 '(erc-dangerous-host-face ((t (:inherit erc-default-face))))
 '(erc-default-face ((nil (:height 110 :family "Anonymous"))))
 '(erc-direct-msg-face ((t (:inherit erc-default-face :foreground "IndianRed"))))
 '(erc-error-face ((t (:inherit erc-default-face))))
 '(erc-fool-face ((t (:inherit erc-default-face :foreground "dim gray"))))
 '(erc-header-line ((t (:inherit erc-default-face))))
 '(erc-input-face ((t (:inherit erc-default-face :foreground "#999999"))))
 '(erc-inverse-face ((t (:inherit erc-default-face :background "Black" :foreground "White"))))
 '(erc-keyword-face ((t (:inherit erc-default-face :foreground "#b58900" :weight bold))))
 '(erc-my-nick-face ((t (:inherit erc-default-face))))
 '(erc-nick-default-face ((t (:inherit erc-default-face :foreground "#268bd2"))))
 '(erc-nick-msg-face ((t (:inherit erc-default-face :foreground "IndianRed" :weight bold))))
 '(erc-notice-face ((t (:inherit erc-default-face :foreground "#2aa198" :weight bold))))
 '(erc-pal-face ((t (:inherit erc-default-face :foreground "Magenta" :weight bold))))
 '(erc-prompt-face ((t (:inherit erc-default-face :background "#073642" :foreground "#DDDD00" :weight bold))))
 '(erc-timestamp-face ((t (:inherit erc-default-face :foreground "#586e75" :weight bold))))
 '(erc-underline-face ((t (:inherit erc-default-face))))
 '(fg:erc-color-face0 ((t (:inherit erc-default-face :foreground "White"))))
 '(font-lock-builtin-face ((((class color) (min-colors 88) (background dark)) (:foreground "#268bd2"))))
 '(font-lock-comment-face ((((class color) (min-colors 88) (background dark)) (:foreground "#cb4b16"))))
 '(font-lock-constant-face ((((class color) (min-colors 88) (background dark)) (:foreground "#d33682"))))
 '(font-lock-function-name-face ((((class color) (min-colors 88) (background dark)) (:foreground "#01d302"))))
 '(font-lock-keyword-face ((((class color) (min-colors 88) (background dark)) (:foreground "#2aa198"))))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face))))
 '(font-lock-string-face ((((class color) (min-colors 88) (background dark)) (:foreground "#b58900"))))
 '(font-lock-type-face ((((class color) (min-colors 88) (background dark)) (:foreground "#268bd2"))))
 '(fringe ((((class color) (background dark)) (:background "#073642"))))
 '(header-line ((default (:inherit mode-line)) (((class color grayscale) (background dark)) (:background "#073642" :foreground "#93a1a1" :box nil))))
 '(highlight ((((class color) (min-colors 88) (background dark)) (:background "#586e75" :foreground "#002b36"))))
 '(link ((((class color) (min-colors 88) (background dark)) (:foreground "#aaccff" :underline t))))
 '(minibuffer-prompt ((((background dark)) (:foreground "#FFFF00"))))
 '(mode-line ((t (:inherit default :background "#073642" :foreground "#93a1a1" :box (:line-width 2 :color "#073642") :weight thin))))
 '(mode-line-buffer-id ((t (:foreground "#268bd2"))))
 '(mode-line-inactive ((default (:inherit mode-line)) (((class color) (min-colors 88) (background dark)) (:background "#073642" :foreground "#586e75" :box (:line-width 2 :color "#073642")))))
 '(region ((((class color) (min-colors 88) (background dark)) (:background "#586e75" :foreground "#eee8d5"))))
 '(secondary-selection ((((class color) (min-colors 88) (background dark)) (:background "#586e75"))))
 '(tooltip ((t (:inherit variable-pitch :background "#839496" :foreground "systeminfotext"))))
 '(vertical-border ((nil (:foreground "#93a1a1"))))))

